apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
  namespace: datadog-demo
  labels:
    app: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
    spec:
      containers:
        - name: service-c
          image: qcodelabsllc/service-c:latest
          ports:
            - containerPort: 8001
          env:
            - name: SERVICE_A_URL
              value: "http://service-a"
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "service-c"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: service-c
  namespace: datadog-demo
spec:
  type: NodePort
  selector:
    app: service-c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001