apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-d
  namespace: datadog-demo
  labels:
    app: service-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-d
  template:
    metadata:
      labels:
        app: service-d
    spec:
      containers:
        - name: service-d
          image: qcodelabsllc/service-b:latest
          ports:
            - containerPort: 8001
          env:
            - name: SERVICE_A_URL
              value: "http://service-a"
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_ENV
              value: "prod"
            - name: DD_SERVICE
              value: "service-d"
            - name: DD_VERSION
              value: "1.0.1"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_TRACE_ANALYTICS_ENABLED
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: service-d
  namespace: datadog-demo
spec:
  type: NodePort
  selector:
    app: service-d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001